export default [
  {
    id: 1,
    new: true,
    name: "Бюстгальтер - Skincare Grey",
    category: "bra",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "s", "m"],
    price: 300,
    mainImg: "./img/bra_skincare_grey_1.jpg",
    images: [
      "../img/bra_skincare_grey_1.jpg",
      "../img/bra_skincare_grey_2.jpg",
      "../img/bra_skincare_grey_3.jpg",
      "../img/bra_skincare_grey_4.jpg",
      "../img/bra_skincare_grey_5.jpg",
    ],
    color: "--grey",
    stock: [
      { id: 1, color: "--grey" },
      { id: 2, color: "--black" },
      { id: 3, color: "--nude" },
      { id: 4, color: "--pink" },
    ],
    description:
      "Бюстгальтер с мягкими чашками одна из самых комфортных моделей для всего периода беременности и грудного вскармливания.",
    composition: "94% нейлон, 6% эластан",
  },
  {
    id: 2,
    new: false,
    name: "Бюстгальтер - Skincare Black",
    category: "bra",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xxl", "xxxl"],
    price: 400,
    mainImg: "./img/bra_skincare_black_1.jpg",
    images: [
      "../img/bra_skincare_black_1.jpg",
      "../img/bra_skincare_black_2.jpg",
      "../img/bra_skincare_black_3.jpg",
      "../img/bra_skincare_black_4.jpg",
      "../img/bra_skincare_black_5.jpg",
    ],
    color: "--black",
    stock: [
      { id: 1, color: "--grey" },
      { id: 2, color: "--black" },
      { id: 3, color: "--nude" },
      { id: 4, color: "--pink" },
    ],
    description:
      "Бюстгальтер с мягкими чашками одна из самых комфортных моделей для всего периода беременности и грудного вскармливания.",
    composition: "94% нейлон, 6% эластан",
  },
  {
    id: 3,
    new: false,
    name: "Бюстгальтер - Skincare Nude",
    category: "bra",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["l", "xl"],
    price: 450,
    mainImg: "./img/bra_skincare_nude_1.jpg",
    images: [
      "../img/bra_skincare_nude_1.jpg",
      "../img/bra_skincare_nude_2.jpg",
      "../img/bra_skincare_nude_3.jpg",
      "../img/bra_skincare_nude_4.jpg",
      "../img/bra_skincare_nude_5.jpg",
      "../img/bra_skincare_nude_6.jpg",
    ],
    color: "--nude",
    stock: [
      { id: 1, color: "--grey" },
      { id: 2, color: "--black" },
      { id: 3, color: "--nude" },
      { id: 4, color: "--pink" },
    ],
    description:
      "Бюстгальтер с мягкими чашками одна из самых комфортных моделей для всего периода беременности и грудного вскармливания.",
    composition: "94% нейлон, 6% эластан",
  },

  {
    id: 4,
    new: false,
    name: "Бюстгальтер - Skincare Pink",
    category: "bra",

    sizes: ["s", "xxxl"],
    price: 500,
    mainImg: "./img/bra_skincare_pink_1.jpg",
    images: [
      "../img/bra_skincare_pink_1.jpg",
      "../img/bra_skincare_pink_2.jpg",
      "../img/bra_skincare_pink_3.jpg",
      "../img/bra_skincare_pink_4.jpg",
      "../img/bra_skincare_pink_5.jpg",
      "../img/bra_skincare_pink_6.jpg",
    ],
    color: "--pink",
    stock: [
      { id: 1, color: "--grey" },
      { id: 2, color: "--black" },
      { id: 3, color: "--nude" },
      { id: 4, color: "--pink" },
    ],
    description:
      "Бюстгальтер с мягкими чашками одна из самых комфортных моделей для всего периода беременности и грудного вскармливания.",
    composition: "94% нейлон, 6% эластан",
  },
  {
    id: 5,
    new: true,
    name: "Дородовый Бандаж - Anita White",
    category: "bandage",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xxxl"],
    price: 550,
    mainImg: "./img/bandage_anita_babybelt_white_1.jpg",
    images: [
      "../img/bandage_anita_babybelt_white_1.jpg",
      "../img/bandage_anita_babybelt_white_2.jpg",
      "../img/bandage_anita_babybelt_white_3.jpg",
      "../img/bandage_anita_babybelt_white_4.jpg",
      "../img/bandage_anita_babybelt_white_5.jpg",
    ],
    color: "--white",
    stock: [
      { id: 5, color: "--white" },
      { id: 6, color: "--nude" },
      { id: 7, color: "--black" },
    ],
    description:
      "Бюстгальтер с мягкими Пояс-бандаж BabyBelt обеспечит эффективную помощь при болях в спине и пояснице. Внутренний вшитый поддерживающий пояс с зонами различной эластичности легко регулируется с помощью застежки-липучки. Бандаж не заметен под одеждой. Ношение в период беременности помогает восстановлению формы живота после родов. одна из самых комфортных моделей для всего периода беременности и грудного вскармливания.",
    composition: "80% полиэстер, 20% эластан",
  },
  {
    id: 6,
    new: false,
    name: "Дородовый Бандаж - Anita Nude",
    category: "bandage",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "l", "xl"],
    price: 600,
    mainImg: "./img/bandage_anita_babybelt_nude_1.jpg",
    images: [
      "../img/bandage_anita_babybelt_nude_1.jpg",
      "../img/bandage_anita_babybelt_nude_2.jpg",
      "../img/bandage_anita_babybelt_nude_3.jpg",
      "../img/bandage_anita_babybelt_nude_4.jpg",
      "../img/bandage_anita_babybelt_nude_5.jpg",
      "../img/bandage_anita_babybelt_nude_6.jpg",
    ],
    color: "--nude",
    stock: [
      { id: 5, color: "--white" },
      { id: 6, color: "--nude" },
      { id: 7, color: "--black" },
    ],
    description:
      "Бюстгальтер с мягкими Пояс-бандаж BabyBelt обеспечит эффективную помощь при болях в спине и пояснице. Внутренний вшитый поддерживающий пояс с зонами различной эластичности легко регулируется с помощью застежки-липучки. Бандаж не заметен под одеждой. Ношение в период беременности помогает восстановлению формы живота после родов. одна из самых комфортных моделей для всего периода беременности и грудного вскармливания.",
    composition: "80% полиэстер, 20% эластан",
  },
  {
    id: 7,
    new: false,
    name: "Дородовый Бандаж - Anita Black",
    category: "bandage",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["s", "xl", "xxxl"],
    price: 650,
    mainImg: "./img/bandage_anita_babybelt_black_1.jpg",
    images: [
      "../img/bandage_anita_babybelt_black_1.jpg",
      "../img/bandage_anita_babybelt_black_2.jpg",
      "../img/bandage_anita_babybelt_black_3.jpg",
      "../img/bandage_anita_babybelt_black_4.jpg",
      "../img/bandage_anita_babybelt_black_5.jpg",
    ],
    color: "--black",
    stock: [
      { id: 5, color: "--white" },
      { id: 6, color: "--nude" },
      { id: 7, color: "--black" },
    ],
    description:
      "Бюстгальтер с мягкими Пояс-бандаж BabyBelt обеспечит эффективную помощь при болях в спине и пояснице. Внутренний вшитый поддерживающий пояс с зонами различной эластичности легко регулируется с помощью застежки-липучки. Бандаж не заметен под одеждой. Ношение в период беременности помогает восстановлению формы живота после родов. одна из самых комфортных моделей для всего периода беременности и грудного вскармливания.",
    composition: "80% полиэстер, 20% эластан",
  },
  {
    id: 8,
    new: true,
    name: "Комплект - Anais Grey",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xl", "xxl", "xxxl"],
    price: 900,
    mainImg: "./img/kit_anais_3.jpg",
    images: [
      "../img/kit_anais_1.jpg",
      "../img/kit_anais_2.jpg",
      "../img/kit_anais_3.jpg",
    ],
    color: "--grey",
    stock: [
      { id: 8, color: "--grey" },
      { id: 9, color: "--pink" },
      { id: 10, color: "--milky" },
      { id: 11, color: "--white" },
      { id: 12, color: "--tiffany" },
    ],
    description:
      "Удобные и красивые комплекты для сна и отдыха для беременных и кормящих мам в роддом, для сна, отдыха и кормления малыша. Можно носить после беременности и грудного вскармливания. Одевайтесь и кормите с удовольствием!",
    composition: "95% хлопок , 5% эластан",
  },
  {
    id: 9,
    new: false,
    name: "Комплект - Anais Pink",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xl"],
    price: 950,
    mainImg: "./img/kit_perla_3.jpg",
    images: [
      "../img/kit_perla_3.jpg",
      "../img/kit_perla_1.jpg",
      "../img/kit_perla_2.jpg",
      "../img/kit_perla_4.jpg",
      "../img/kit_perla_5.jpg",
      "../img/kit_perla_6.jpg",
      "../img/kit_perla_7.jpg",
      "../img/kit_perla_8.jpg",
    ],
    color: "--pink",
    stock: [
      { id: 8, color: "--grey" },
      { id: 9, color: "--pink" },
      { id: 10, color: "--milky" },
      { id: 11, color: "--white" },
      { id: 12, color: "--tiffany" },
    ],
    description:
      "Удобные и красивые комплекты для сна и отдыха для беременных и кормящих мам в роддом, для сна, отдыха и кормления малыша. Можно носить после беременности и грудного вскармливания. Одевайтесь и кормите с удовольствием!",
    composition: "95% хлопок , 5% эластан",
  },
  {
    id: 10,
    new: false,
    name: "Комплект - Anais Milki",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "m"],
    price: 1000,
    mainImg: "./img/kit_milki_2.jpg",
    images: [
      "../img/kit_milki_2.jpg",
      "../img/kit_milki_1.jpg",
      "../img/kit_milki_3.jpg",
      "../img/kit_milki_4.jpg",
      "../img/kit_milki_5.jpg",
      "../img/kit_milki_6.jpg",
      "../img/kit_milki_7.jpg",
      "../img/kit_milki_8.jpg",
    ],
    color: "--milky",
    stock: [
      { id: 8, color: "--grey" },
      { id: 9, color: "--pink" },
      { id: 10, color: "--milky" },
      { id: 11, color: "--white" },
      { id: 12, color: "--tiffany" },
    ],
    description:
      "Удобные и красивые комплекты для сна и отдыха для беременных и кормящих мам в роддом, для сна, отдыха и кормления малыша. Можно носить после беременности и грудного вскармливания. Одевайтесь и кормите с удовольствием!",
    composition: "95% хлопок , 5% эластан",
  },
  {
    id: 11,
    new: false,
    name: "Комплект - Anais Provance",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["l", "xl"],
    price: 1100,
    mainImg: "./img/kit_provance_8.jpg",
    images: [
      "../img/kit_provance_8.jpg",
      "../img/kit_provance_1.jpg",
      "../img/kit_provance_2.jpg",
      "../img/kit_provance_3.jpg",
      "../img/kit_provance_4.jpg",
      "../img/kit_provance_5.jpg",
      "../img/kit_provance_6.jpg",
      "../img/kit_provance_7.jpg",
    ],
    color: "--white",
    stock: [
      { id: 8, color: "--grey" },
      { id: 9, color: "--pink" },
      { id: 10, color: "--milky" },
      { id: 11, color: "--white" },
      { id: 12, color: "--tiffany" },
    ],
    description:
      "Удобные и красивые комплекты для сна и отдыха для беременных и кормящих мам в роддом, для сна, отдыха и кормления малыша. Можно носить после беременности и грудного вскармливания. Одевайтесь и кормите с удовольствием!",
    composition: "95% хлопок , 5% эластан",
  },
  {
    id: 12,
    new: false,
    name: "Комплект - Anais Tiffany",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["s", "m", "xxxl"],
    price: 1200,
    mainImg: "./img/kit_tiffany_6.jpg",
    images: [
      "../img/kit_tiffany_6.jpg",
      "../img/kit_tiffany_1.jpg",
      "../img/kit_tiffany_2.jpg",
      "../img/kit_tiffany_3.jpg",
      "../img/kit_tiffany_4.jpg",
      "../img/kit_tiffany_5.jpg",
      "../img/kit_tiffany_7.jpg",
      "../img/kit_tiffany_8.jpg",
    ],
    color: "--tiffany",
    stock: [
      { id: 8, color: "--grey" },
      { id: 9, color: "--pink" },
      { id: 10, color: "--milky" },
      { id: 11, color: "--white" },
      { id: 12, color: "--tiffany" },
    ],
    description:
      "Удобные и красивые комплекты для сна и отдыха для беременных и кормящих мам в роддом, для сна, отдыха и кормления малыша. Можно носить после беременности и грудного вскармливания. Одевайтесь и кормите с удовольствием!",
    composition: "95% хлопок , 5% эластан",
  },
  {
    id: 13,
    new: true,
    name: "Трусики-бандаж - MumsCare Pink",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["l", "xl", "xxl", "xxxl"],
    price: 250,
    mainImg: "./img/panties_pink_1.jpg",
    images: [
      "../img/panties_pink_1.jpg",
      "../img/panties_pink_2.jpg",
      "../img/panties_pink_3.jpg",
      "../img/panties_pink_4.jpg",
    ],
    color: "--pink",
    stock: [
      { id: 13, color: "--pink" },
      { id: 14, color: "--grey" },
      { id: 15, color: "--nude" },
      { id: 16, color: "--black" },
    ],
    description:
      "Рекомендуем с первых дней после родов до полного восстановления.Корректирующие трусики Comfort это твое бережное восстановление после родов.Способствуют мягкому восстановлению тонуса мышц и кожи живота после родов",
    composition: "полиестер, вкладка – хлопок.",
  },
  {
    id: 14,
    new: false,
    name: "Трусики-бандаж - MumsCare Grey",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "s", "m"],
    price: 300,
    mainImg: "./img/panties_grey_1.jpg",
    images: [
      "../img/panties_grey_1.jpg",
      "../img/panties_grey_2.jpg",
      "../img/panties_grey_3.jpg",
      "../img/panties_grey_4.jpg",
    ],
    color: "--grey",
    stock: [
      { id: 13, color: "--pink" },
      { id: 14, color: "--grey" },
      { id: 15, color: "--nude" },
      { id: 16, color: "--black" },
    ],
    description:
      "Рекомендуем с первых дней после родов до полного восстановления.Корректирующие трусики Comfort это твое бережное восстановление после родов.Способствуют мягкому восстановлению тонуса мышц и кожи живота после родов",
    composition: "полиестер, вкладка – хлопок.",
  },
  {
    id: 15,
    new: false,
    name: "Трусики-бандаж - MumsCare Nude",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xl"],
    price: 350,
    mainImg: "./img/panties_nude_1.jpg",
    images: [
      "../img/panties_nude_1.jpg",
      "../img/panties_nude_2.jpg",
      "../img/panties_nude_3.jpg",
      "../img/panties_nude_4.jpg",
    ],
    color: "--nude",
    stock: [
      { id: 13, color: "--pink" },
      { id: 14, color: "--grey" },
      { id: 15, color: "--nude" },
      { id: 16, color: "--black" },
    ],
    description:
      "Рекомендуем с первых дней после родов до полного восстановления.Корректирующие трусики Comfort это твое бережное восстановление после родов.Способствуют мягкому восстановлению тонуса мышц и кожи живота после родов",
    composition: "полиестер, вкладка – хлопок.",
  },
  {
    id: 16,
    new: false,
    name: "Трусики-бандаж - MumsCare Black",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xxxl"],
    price: 400,
    mainImg: "./img/panties_black_1.jpg",
    images: [
      "../img/panties_black_1.jpg",
      "../img/panties_black_2.jpg",
      "../img/panties_black_3.jpg",
      "../img/panties_black_4.jpg",
    ],
    color: "--black",
    stock: [
      { id: 13, color: "--pink" },
      { id: 14, color: "--grey" },
      { id: 15, color: "--nude" },
      { id: 16, color: "--black" },
    ],
    description:
      "Рекомендуем с первых дней после родов до полного восстановления.Корректирующие трусики Comfort это твое бережное восстановление после родов.Способствуют мягкому восстановлению тонуса мышц и кожи живота после родов",
    composition: "полиестер, вкладка – хлопок.",
  },
];

// {
//   name: "",
//   category: ["", "all"],
//   sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
//   price: "",
//   mainImg: "",
// },
