export default [
  {
    name: "Бюстгальтер - Skincare Grey",
    category: "bra",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "s", "m"],
    price: 300,
    mainImg: "./img/bra_skincare_grey_1.jpg",
  },
  {
    name: "Бюстгальтер - Skincare Black",
    category: "bra",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xxl", "xxxl"],
    price: 400,
    mainImg: "./img/bra_skincare_black_1.jpg",
  },
  {
    name: "Бюстгальтер - Skincare Nude",
    category: "bra",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["l", "xl"],
    price: 450,
    mainImg: "./img/bra_skincare_nude_1.jpg",
  },
  {
    name: "Бюстгальтер - Skincare Pink",
    category: "bra",

    sizes: ["s", "xxxl"],
    price: 500,
    mainImg: "./img/bra_skincare_pink_1.jpg",
  },
  {
    name: "Дородовый Бандаж - Anita White",
    category: "bandage",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xxxl"],
    price: 550,
    mainImg: "./img/bandage_anita_babybelt_white_1.jpg",
  },
  {
    name: "Дородовый Бандаж - Anita Nude",
    category: "bandage",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "l", "xl"],
    price: 600,
    mainImg: "./img/bandage_anita_babybelt_nude_1.jpg",
  },
  {
    name: "Дородовый Бандаж - Anita Black",
    category: "bandage",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["s", "xl", "xxxl"],
    price: 650,
    mainImg: "./img/bandage_anita_babybelt_black_1.jpg",
  },
  {
    name: "Комплект - Anais Grey",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xl", "xxl", "xxxl"],
    price: 900,
    mainImg: "./img/kit_anais_2.jpg",
  },
  {
    name: "Комплект - Anais Pink",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xl"],
    price: 950,
    mainImg: "./img/kit_perla_3.jpg",
  },
  {
    name: "Комплект - Anais Milki",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "m"],
    price: 1000,
    mainImg: "./img/kit_milki_2.jpg",
  },
  {
    name: "Комплект - Anais Provance",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["l", "xl"],
    price: 1100,
    mainImg: "./img/kit_provance_8.jpg",
  },
  {
    name: "Комплект - Anais Tiffany",
    category: "kit",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["s", "m", "xxxl"],
    price: 1200,
    mainImg: "./img/kit_tiffany_6.jpg",
  },
  {
    name: "Трусики-бандаж - MumsCare Pink",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["l", "xl", "xxl", "xxxl"],
    price: 250,
    mainImg: "./img/panties_pink_1.jpg",
  },
  {
    name: "Трусики-бандаж - MumsCare Grey",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["xs", "s", "m"],
    price: 300,
    mainImg: "./img/panties_grey_1.jpg",
  },
  {
    name: "Трусики-бандаж - MumsCare Nude",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xl"],
    price: 350,
    mainImg: "./img/panties_nude_1.jpg",
  },
  {
    name: "Трусики-бандаж - MumsCare Black",
    category: "panties",
    // sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
    sizes: ["m", "l", "xxxl"],
    price: 400,
    mainImg: "./img/panties_black_1.jpg",
  },
];

// {
//   name: "",
//   category: ["", "all"],
//   sizes: ["xs", "s", "m", "l", "xl", "xxl", "xxxl"],
//   price: "",
//   mainImg: "",
// },
